### ISSUE TITLE
The dbslmm binary is missing

### ISSUE THREAD

**Issue by opain** [biostat0903/DBSLMM#21]
Hello, I noticed the dbslmm binary file was deleted in commit 99e2ea37d932744bf1b739b65da6dc27b0901745.

Is this a mistake, or has the way to run dbslmm changed?

Many thanks,

Ollie

**Comment by biostat0903** [comment]
Hi Ollie, 
Thanks for your attention to DBSLMM. There are some modification for binary file of DBSLMM. We use the weighted LD matrix in new version of  `dbslmm`. In my experience, this version might be better than the old version. 
Sorry for the inconvenience brought to you
Best, 
Sheng

**Comment by opain** [comment]
Hi Sheng,

Thank you for your fast response. The modification sounds good, but I am still unsure where I can find the dbslmm binary. It used to be within the 'software' folder, along with the R scripts. Do I need to compilile my own version of the dbslmm binary, or are you yet to release the new version?

Many thanks,

Ollie

**Comment by biostat0903** [comment]
Hi Ollie, 
I give the download linkage: https://drive.google.com/file/d/1eAbEyhF8rO_faOFL3jqRo9LmfgJNRH6K/view?usp=sharing.
If you give me your e-mail, I can send it to you. 
Best, 
Sheng

**Comment by opain** [comment]
Hi Sheng, 

Many thanks. The link works.

Presumably the dbslmm binary will be included in the DBSLMM repo again in the future?

Best wishes,

Ollie

**Comment by biostat0903** [comment]
Hi Ollie, 
Thanks for your consideration to DBSLMM. Because the executable file of `dbslmm` is large than 25Mb, I upload it to google drive. Sorry for the inconvenience brought to you. 
By the way, I build a web-server (PGS-Server) which can fit to different PGS construction model. The website is www.pgs-server.com. If there are any problem of the server, you can leave massage at https://github.com/biostat0903/PGS-Server/issues. Your suggestions can improve the server. 
Thanks for your help again. 
Best, 
Sheng

**Comment by opain** [comment]
Hi Sheng,

OK, good to know about the binary. Thank you.

Wow, PGS-Server looks brilliant. Nice work. I look forward to trying it out.

Many thanks,

Ollie
